import Link from "next/link";

export const metadata = {
  title: "Terms of Service — AWT Cloud",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="mb-2 text-3xl font-bold text-gray-900">Terms of Service</h1>
      <p className="mb-8 text-sm text-gray-500">Last updated: February 24, 2026</p>

      <div className="prose prose-gray max-w-none text-gray-700 [&_h2]:mt-8 [&_h2]:mb-3 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-gray-900 [&_h3]:mt-6 [&_h3]:mb-2 [&_h3]:text-lg [&_h3]:font-medium [&_h3]:text-gray-800 [&_p]:mb-3 [&_p]:leading-relaxed [&_ul]:mb-3 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mb-1">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using AWT Cloud (&quot;the Service&quot;), operated by AWT (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;),
          you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          AWT Cloud is an AI-powered end-to-end testing platform that generates, executes, and manages
          automated test scenarios for websites. The Service includes:
        </p>
        <ul>
          <li>AI-driven test scenario generation from URLs and documents</li>
          <li>Automated browser-based test execution with Playwright</li>
          <li>Real-time test monitoring with live screenshots</li>
          <li>Test result reports and history</li>
          <li>API access for CI/CD integration</li>
        </ul>

        <h2>3. Accounts and Registration</h2>
        <p>
          You must create an account to use the Service. You are responsible for maintaining the
          confidentiality of your credentials and for all activities under your account.
          You must provide accurate information and promptly update it if it changes.
        </p>

        <h2>4. Subscription Plans</h2>
        <h3>4.1 Free Plan</h3>
        <p>
          The Free plan includes up to 5 tests per month and 1 concurrent test.
          No credit card is required. We reserve the right to modify Free plan limits at any time.
        </p>
        <h3>4.2 Paid Plans (Pro, Team)</h3>
        <p>
          Paid plans are billed monthly. Payments are processed through our payment partner (Lemon Squeezy).
          You may cancel at any time; access continues until the end of the billing period.
          Refunds are handled per our payment partner&apos;s refund policy.
        </p>
        <h3>4.3 Usage Limits</h3>
        <p>
          Each plan has monthly test limits and concurrent execution limits.
          Exceeding these limits will result in requests being rejected until the next billing cycle
          or an upgrade to a higher plan.
        </p>

        <h2>5. Bring Your Own Key (BYOK)</h2>
        <p>
          You may optionally provide your own AI API key (e.g., OpenAI, Anthropic) through the Settings page.
          Your API keys are encrypted using Fernet symmetric encryption before being stored in our database.
          The encryption key is managed server-side and never exposed to clients.
        </p>
        <p>
          We do not use your API keys for any purpose other than generating test scenarios on your behalf.
          You may delete your stored key at any time, reverting to the server default AI provider.
          You are solely responsible for any costs incurred through your own API keys.
        </p>

        <h2>6. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to test websites you do not own or have authorization to test</li>
          <li>Attempt to overload, disrupt, or exploit the Service infrastructure</li>
          <li>Use the Service for illegal activities, including unauthorized penetration testing</li>
          <li>Circumvent usage limits, rate limiting, or authentication mechanisms</li>
          <li>Resell or redistribute the Service without written permission</li>
        </ul>

        <h2>7. Intellectual Property</h2>
        <p>
          The Service, including its source code (MIT licensed), documentation, and branding, is our property.
          Test scenarios generated by the AI are provided for your use and may be freely modified.
          You retain ownership of your test data, documents, and configurations.
        </p>

        <h2>8. Data and Privacy</h2>
        <p>
          Your use of the Service is also governed by our{" "}
          <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>.
          We process screenshots, test results, and uploaded documents solely to provide the Service.
        </p>

        <h2>9. Service Availability</h2>
        <p>
          We strive for high availability but do not guarantee uninterrupted service.
          The Service is provided &quot;as is&quot; without warranties of any kind, express or implied.
          We are not liable for damages arising from service interruptions, data loss, or test inaccuracies.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, our total liability for any claims arising from
          the Service is limited to the amount you paid us in the 12 months preceding the claim.
          We are not liable for indirect, incidental, special, or consequential damages.
        </p>

        <h2>11. Termination</h2>
        <p>
          We may suspend or terminate your account if you violate these Terms.
          You may delete your account at any time. Upon termination, your data will be deleted
          within 30 days, except as required by law.
        </p>

        <h2>12. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. Material changes will be communicated via
          email or in-app notification. Continued use after changes constitutes acceptance.
        </p>

        <h2>13. Contact</h2>
        <p>
          For questions about these Terms, contact us at{" "}
          <a href="mailto:awt.dev.team@gmail.com" className="text-blue-600 hover:underline">awt.dev.team@gmail.com</a>.
        </p>
      </div>
    </div>
  );
}
